### ISSUE TITLE
A fresh subnetwork has no interface bound to it. If one uses dnsmasq together this this, it will create a failure in dnsmasq because it cant bind dnsmasq to the bridge

### ISSUE THREAD

**Issue by do3cc** [debops/ansible-subnetwork#4]

**Comment by drybjed** [comment]
`debops.subnetwork` is designed to by default create an internal bridged network (NAT), which does not need to be bound to any real network interface. You can of course still do it using `subnetwork_bridge_ports` list to for example create a router for a bunch of machines behind an internal Ethernet interface.

My internal network does not have a real interface bound to the bridge:

```
# Contents of /etc/network/interfaces:
# Configuration for br2 bridge
auto br2
iface br2 inet static
        address        192.168.128.1
        network        192.168.128.0
        netmask        255.255.255.0
        broadcast      192.168.128.255
        bridge_ports   none
        bridge_stp     on
        bridge_fd      0
        bridge_maxwait 0

# This file is managed by Ansible, all changes will be lost

# Configuration for br2 interface
iface br2 inet6 static
        pre-up echo 0 > /proc/sys/net/ipv6/conf/br2/accept_dad
        address 2002:xxxx:xxxx:deb0::1/64
```
```
# brctl show:
bridge name     bridge id               STP enabled     interfaces
br2             8000.fe5400095ccd       yes             vnet0
                                                        vnet1
```
```
# ip route show:
169.254.0.0/16 dev br2  scope link  metric 1000 
192.168.128.0/24 dev br2  proto kernel  scope link  src 192.168.128.1 
```
I'm not sure what's the problem here, but I think the `dnsmasq` configuration might be at fault, not the bridge itself.

**Comment by do3cc** [comment]
Yes, I'm pretty sure now it is dnsmaq problem. Not necessarily config but version

On 13. Januar 2015 09:07:21 MEZ, Maciej Delmanowski <notifications@github.com> wrote:
>`debops.subnetwork` is designed to by default create an internal
>bridged network (NAT), which does not need to be bound to any real
>network interface. You can of course still do it using
>`subnetwork_bridge_ports` list to for example create a router for a
>bunch of machines behind an internal Ethernet interface.
>
>My internal network does not have a real interface bound to the bridge:
>
>```
># Contents of /etc/network/interfaces:
># Configuration for br2 bridge
>auto br2
>iface br2 inet static
>        address        192.168.128.1
>        network        192.168.128.0
>        netmask        255.255.255.0
>        broadcast      192.168.128.255
>        bridge_ports   none
>        bridge_stp     on
>        bridge_fd      0
>        bridge_maxwait 0
>
># This file is managed by Ansible, all changes will be lost
>
># Configuration for br2 interface
>iface br2 inet6 static
>        pre-up echo 0 > /proc/sys/net/ipv6/conf/br2/accept_dad
>        address 2002:xxxx:xxxx:deb0::1/64
>```
>```
># brctl show:
>bridge name     bridge id               STP enabled     interfaces
>br2             8000.fe5400095ccd       yes             vnet0
>                                                        vnet1
>```
>```
># ip route show:
>169.254.0.0/16 dev br2  scope link  metric 1000 
>192.168.128.0/24 dev br2  proto kernel  scope link  src 192.168.128.1 
>```
>I'm not sure what's the problem here, but I think the `dnsmasq`
>configuration might be at fault, not the bridge itself.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/debops/ansible-subnetwork/issues/4#issuecomment-69708696

-- 
Diese Nachricht wurde von meinem Mobiltelefon mit Kaiten Mail gesendet.

**Comment by ypid** [comment]
@do3cc  I think you can close this issue.

**Comment by do3cc** [comment]
@ypid I cannot test this any more.
Are you saying that this problem does not appear any more?

**Comment by ypid** [comment]
I used this role together with dnsmasq and am not able to reproduce your problem.

**Comment by do3cc** [comment]
Thanks!
I believe the issue was the older debian version at that time.
